import { Document, Types } from 'mongoose';

// ─── Audit Event Types ────────────────────────────────────────────────────────
export enum AuditAction {
    // Auth events
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
    USER_LOGOUT = 'USER_LOGOUT',

    // Password events
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',     // user changed their own password
    PASSWORD_RESET = 'PASSWORD_RESET',        // super-admin force-reset

    // Account / company events
    COMPANY_CREATED = 'COMPANY_CREATED',
    COMPANY_UPDATED = 'COMPANY_UPDATED',
    COMPANY_SUSPENDED = 'COMPANY_SUSPENDED',
    COMPANY_ACTIVATED = 'COMPANY_ACTIVATED',
    COMPANY_DELETED = 'COMPANY_DELETED',

    // Subscription events
    SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
    SUBSCRIPTION_UPGRADED = 'SUBSCRIPTION_UPGRADED',
    SUBSCRIPTION_DOWNGRADED = 'SUBSCRIPTION_DOWNGRADED',
    SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED',
    SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',

    // Project events
    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',
    PROJECT_UNARCHIVED = 'PROJECT_UNARCHIVED',
    PROJECT_DELETED = 'PROJECT_DELETED',
    PROJECT_PINNED = 'PROJECT_PINNED',
    PROJECT_UNPINNED = 'PROJECT_UNPINNED',
    PROJECT_ACTIVATED = 'PROJECT_ACTIVATED',
    PROJECT_DEACTIVATED = 'PROJECT_DEACTIVATED',

    // Wishlist events
    WISHLIST_CREATED = 'WISHLIST_CREATED',
    WISHLIST_UPDATED = 'WISHLIST_UPDATED',
    WISHLIST_STATUS_CHANGED = 'WISHLIST_STATUS_CHANGED',
    WISHLIST_CONVERTED_TO_TASK = 'WISHLIST_CONVERTED_TO_TASK',
    WISHLIST_DELETED = 'WISHLIST_DELETED',

    // Sprint events
    SPRINT_CREATED = 'SPRINT_CREATED',
    SPRINT_UPDATED = 'SPRINT_UPDATED',
    SPRINT_STARTED = 'SPRINT_STARTED',
    SPRINT_COMPLETED = 'SPRINT_COMPLETED',
    SPRINT_CANCELLED = 'SPRINT_CANCELLED',
    SPRINT_DELETED = 'SPRINT_DELETED',

    // Release events
    RELEASE_CREATED = 'RELEASE_CREATED',
    RELEASE_UPDATED = 'RELEASE_UPDATED',
    RELEASE_STARTED = 'RELEASE_STARTED',
    RELEASE_RELEASED = 'RELEASE_RELEASED',
    RELEASE_CANCELLED = 'RELEASE_CANCELLED',
    RELEASE_DELETED = 'RELEASE_DELETED',

    // Task relationship events
    TASK_ASSIGNED_TO_SPRINT = 'TASK_ASSIGNED_TO_SPRINT',
    TASK_ASSIGNED_TO_RELEASE = 'TASK_ASSIGNED_TO_RELEASE',
    TASK_REMOVED_FROM_SPRINT = 'TASK_REMOVED_FROM_SPRINT',
    TASK_REMOVED_FROM_RELEASE = 'TASK_REMOVED_FROM_RELEASE',

    // Generic
    OTHER = 'OTHER',
    USER_PERMISSIONS_UPDATED = 'USER_PERMISSIONS_UPDATED',
    USER_PERFORMANCE_VIEW = 'USER_PERFORMANCE_VIEW',

    // Impersonation
    IMPERSONATION_STARTED = 'IMPERSONATION_STARTED',
    IMPERSONATION_ENDED = 'IMPERSONATION_ENDED',
    IMPERSONATION_EXPIRED = 'IMPERSONATION_EXPIRED',

    // MFA events
    MFA_SETUP_INITIATED = 'MFA_SETUP_INITIATED',
    MFA_ENABLED = 'MFA_ENABLED',
    MFA_DISABLED = 'MFA_DISABLED',
    MFA_VERIFY_SUCCESS = 'MFA_VERIFY_SUCCESS',
    MFA_VERIFY_FAILED = 'MFA_VERIFY_FAILED',
    MFA_RECOVERY_USED = 'MFA_RECOVERY_USED',
    MFA_RECOVERY_CODES_REGENERATED = 'MFA_RECOVERY_CODES_REGENERATED',

    // Session events
    SESSION_REVOKED = 'SESSION_REVOKED',
    ALL_SESSIONS_REVOKED = 'ALL_SESSIONS_REVOKED',

    // Meeting events
    MEETING_CREATED = 'MEETING_CREATED',
    MEETING_ACCEPTED = 'MEETING_ACCEPTED',
    MEETING_REJECTED = 'MEETING_REJECTED',
    MEETING_RESCHEDULE_REQUESTED = 'MEETING_RESCHEDULE_REQUESTED',
    MEETING_RESCHEDULE_ACCEPTED = 'MEETING_RESCHEDULE_ACCEPTED',
    MEETING_RESCHEDULE_REJECTED = 'MEETING_RESCHEDULE_REJECTED',
    MEETING_CANCELLED = 'MEETING_CANCELLED',
    MEETING_JOINED = 'MEETING_JOINED',

    // Sticky note events
    STICKY_NOTE_CREATED = 'STICKY_NOTE_CREATED',
    STICKY_NOTE_UPDATED = 'STICKY_NOTE_UPDATED',
    STICKY_NOTE_DELETED = 'STICKY_NOTE_DELETED',
    STICKY_NOTE_RESTORED = 'STICKY_NOTE_RESTORED',
    STICKY_NOTE_ARCHIVED = 'STICKY_NOTE_ARCHIVED',
    STICKY_NOTE_COMPLETED = 'STICKY_NOTE_COMPLETED',
    STICKY_NOTE_CONVERTED_TO_TASK = 'STICKY_NOTE_CONVERTED_TO_TASK',

    // Notification sound events
    NOTIFICATION_SOUND_CREATED = 'NOTIFICATION_SOUND_CREATED',
    NOTIFICATION_SOUND_UPDATED = 'NOTIFICATION_SOUND_UPDATED',
    NOTIFICATION_SOUND_DELETED = 'NOTIFICATION_SOUND_DELETED',
    NOTIFICATION_SOUND_MAPPING_CREATED = 'NOTIFICATION_SOUND_MAPPING_CREATED',
    NOTIFICATION_SOUND_MAPPING_UPDATED = 'NOTIFICATION_SOUND_MAPPING_UPDATED',
    NOTIFICATION_SOUND_DISABLED = 'NOTIFICATION_SOUND_DISABLED',
    DEFAULT_NOTIFICATION_SOUND_CHANGED = 'DEFAULT_NOTIFICATION_SOUND_CHANGED',
}

// ─── Mongoose Document Interface ──────────────────────────────────────────────
export interface IAuditLogDocument extends Document {
    action: AuditAction;
    /** The user who performed the action (may be null for system events) */
    actorId: Types.ObjectId | null;
    actorEmail: string | null;
    actorRole: string | null;
    /** Target user affected by the action (e.g. the user whose password was reset) */
    targetUserId: Types.ObjectId | null;
    targetEmail: string | null;
    /** Company context */
    companyId: Types.ObjectId | null;
    companyName: string | null;
    /** Extra context (IP, device, reason, etc.) */
    metadata: Record<string, any>;
    /** HTTP request IP address */
    ipAddress: string | null;
    userAgent: string | null;
    /** Whether the action succeeded */
    success: boolean;
    /** Human-readable description */
    description: string;
    createdAt: Date;
    updatedAt: Date;
}
